### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by hdrpknc**
1. [x] Added the correct info
2. [x] Stared the repo :wink:
3. [x] Looked over the Code of Conduct and this content is inline with it

### CODE REVIEW

**Comment by StevenCopeland** [comment]
@hdrpknc  Congrats on your first PR!

**Comment by hdrpknc** [comment]
I think somehow the sections aren't right anymore. But I don't know why

**Comment by StevenCopeland** [comment]
which sections?

**Comment by hdrpknc** [comment]
Sorry, i didn't explain it good. I mean the readme file used to look like:

Name: Joe Bob 
Bio: I am a great guy! 
Place: City of the Joe 
Website: joethecannonball.fakewebsite.com 
Twitter: JoeBobTheCannonFakeUser 
Facebook: JoeBobTheCannonFakeUser


But now it looks like:

Name: Joe Bob Bio: I am a great guy! Place: City of the Joe Website: joethecannonball.fakewebsite.com Twitter: JoeBobTheCannonFakeUser Facebook: JoeBobTheCannonFakeUser

**Comment by StevenCopeland** [comment]
That is because some one replaced the readme with out two space indent after each item.

**Comment by hdrpknc** [comment]
I used sublime Text for editing. My guess is somehow sublime did this. But
on  my local Maschine it still looks right.

Am 19.10.2017 11:52 nachm. schrieb "Steven Copeland" <
notifications@github.com>:

**Comment by StevenCopeland** [comment]
Oh no! Now I have to go and add two space indent after every thing!

**Comment by StevenCopeland** [comment]
Don't worry about it. I'll can do that pretty easily. If you want to do it then you can create a new PR with the new content. Also, I recommend Atom.

**Comment by hdrpknc** [comment]
Sure, i will fix that.

Am 20.10.2017 12:00 vorm. schrieb "Steven Copeland" <
notifications@github.com>:

**Pull request merged**
